import type { Config } from 'tailwindcss'

export default {
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // ── Legacy tokens (kept for backward compat) ─────────────
        green: { DEFAULT: '#1DB954', light: '#1ED760', dark: '#169C46' },
        black: { deep: '#0e0e0e', surface: '#201f1f', failed: '#191414' },
        gray: { body: '#535353', light: '#B3B3B3' },
        // ── Sonic Monolith design tokens ──────────────────────────
        'primary':                  '#53e076',
        'primary-container':        '#1db954',
        'primary-fixed':            '#72fe8f',
        'primary-fixed-dim':        '#53e076',
        'on-primary':               '#003914',
        'on-primary-container':     '#004118',
        'on-primary-fixed':         '#002108',
        'on-primary-fixed-variant': '#005320',
        'secondary':                '#c8c6c5',
        'secondary-container':      '#474746',
        'secondary-fixed':          '#e4e2e1',
        'secondary-fixed-dim':      '#c8c6c5',
        'on-secondary':             '#303030',
        'on-secondary-container':   '#b7b5b4',
        'on-secondary-fixed':       '#1b1c1c',
        'on-secondary-fixed-variant':'#474746',
        'tertiary':                 '#c8c6c6',
        'tertiary-container':       '#a2a1a1',
        'tertiary-fixed':           '#e4e2e2',
        'tertiary-fixed-dim':       '#c8c6c6',
        'on-tertiary':              '#303030',
        'on-tertiary-container':    '#383838',
        'on-tertiary-fixed':        '#1b1c1c',
        'on-tertiary-fixed-variant':'#474747',
        'surface':                  '#131313',
        'surface-dim':              '#131313',
        'surface-bright':           '#393939',
        'surface-container-lowest': '#0e0e0e',
        'surface-container-low':    '#1c1b1b',
        'surface-container':        '#201f1f',
        'surface-container-high':   '#2a2a2a',
        'surface-container-highest':'#353534',
        'surface-variant':          '#353534',
        'surface-tint':             '#53e076',
        'on-surface':               '#e5e2e1',
        'on-surface-variant':       '#bccbb9',
        'on-background':            '#e5e2e1',
        'background':               '#131313',
        'outline':                  '#869585',
        'outline-variant':          '#3d4a3d',
        'inverse-surface':          '#e5e2e1',
        'inverse-on-surface':       '#313030',
        'inverse-primary':          '#006e2d',
        'error':                    '#ffb4ab',
        'error-container':          '#93000a',
        'on-error':                 '#690005',
        'on-error-container':       '#ffdad6',
      },
      fontFamily: {
        headline: ['Space Grotesk', 'sans-serif'],
        body:     ['Newsreader', 'Georgia', 'serif'],
        label:    ['Space Grotesk', 'sans-serif'],
        // Legacy
        mono:  ['"Courier New"', 'monospace'],
        serif: ['Georgia', 'serif'],
      },
      borderRadius: {
        none:    '0',
        sm:      '0.5rem',
        DEFAULT: '1rem',
        lg:      '2rem',
        xl:      '3rem',
        full:    '9999px',
      },
      spacing: {
        '1': '4px', '2': '8px', '4': '16px',
        '6': '24px', '12': '48px', '20': '80px',
      },
      maxWidth: { content: '640px' },
    },
  },
  plugins: [],
} satisfies Config
